server:
  port: ${SERVER_PORT:0}

spring:
  application:
    name: COURSE-SERVICE
  datasource:
    url: ${DB_PASSWORD}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    change-log: db/changelog/changelog.xml
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_URI}
          issuer-uri: ${KEYCLOAK_ISSUER_URI}


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

logging:
  level:
    root: info
    org.andarworld.courseservice: debug